import '../mo_hinh/nha_hang.dart';
final List<NhaHang> dsNhaHang = const [
  NhaHang(
    id: 'r1',
    ten: 'Ẩm Thực Sài Gòn',
    thanhPho: 'TP. Hồ Chí Minh',
    amThuc: 'Việt Nam',
    diaChi: '12 Nguyễn Huệ, Q.1',
    danhGia: 4.6,
    anh: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1200',
    moTa: 'Không gian hiện đại, phù hợp họp mặt gia đình và bạn bè.',
  ),
  NhaHang(
    id: 'r2',
    ten: 'Hà Nội Corner',
    thanhPho: 'Hà Nội',
    amThuc: 'Bắc',
    diaChi: '88 Phố Cổ, Hoàn Kiếm',
    danhGia: 4.4,
    anh: 'https://images.unsplash.com/photo-1541542684-4a6563d89d8d?q=80&w=1200',
    moTa: 'Đậm chất truyền thống với món phở và bún chả nổi tiếng.',
  ),
  NhaHang(
    id: 'r3',
    ten: 'Tokyo Sushi',
    thanhPho: 'Đà Nẵng',
    amThuc: 'Nhật',
    diaChi: '5 Võ Nguyên Giáp',
    danhGia: 3,
    anh: 'https://images.unsplash.com/photo-1553621042-f6e147245754?q=80&w=1200',
    moTa: 'Sushi tươi mỗi ngày, view biển thoáng đãng.',
  ),
  NhaHang(
    id: 'r4',
    ten: 'Pasta Fresca',
    thanhPho: 'TP. Hồ Chí Minh',
    amThuc: 'Ý',
    diaChi: '25 Lê Lợi, Q.1',
    danhGia: 1,
    anh: 'https://images.unsplash.com/photo-1526382551041-3c817fc3d478?q=80&w=1200',
    moTa: 'Mì Ý handmade và rượu vang tuyển chọn.',
  ),
  NhaHang(
    id: 'r5',
    ten: 'K-BBQ House',
    thanhPho: 'Hà Nội',
    amThuc: 'Hàn',
    diaChi: '101 Kim Mã, Ba Đình',
    danhGia: 2,
    anh: 'https://images.unsplash.com/photo-1553621042-4cc12f5d2b32?q=80&w=1200',
    moTa: 'Thịt nướng chuẩn vị Hàn, không gian rộng rãi.',
  ),
];